/* 새 테이블 */
DROP TABLE TITLE 
	CASCADE CONSTRAINTS;

/* 부서 */
DROP TABLE DEPARTMENT 
	CASCADE CONSTRAINTS;

/* 사원 */
DROP TABLE EMPLOYEE 
	CASCADE CONSTRAINTS;

/* 새 테이블 */
CREATE TABLE TITLE (
	TITLE_NO NUMBER NOT NULL, /* 직책번호 */
	TITLE_NAME VARCHAR2(10) NOT NULL /* 직책명 */
);

COMMENT ON TABLE TITLE IS '새 테이블';

COMMENT ON COLUMN TITLE.TITLE_NO IS '직책번호';

COMMENT ON COLUMN TITLE.TITLE_NAME IS '직책명';

CREATE UNIQUE INDEX PK_TITLE
	ON TITLE (
		TITLE_NO ASC
	);

CREATE UNIQUE INDEX UIX_TITLE
	ON TITLE (
		TITLE_NAME ASC
	);

ALTER TABLE TITLE
	ADD
		CONSTRAINT PK_TITLE
		PRIMARY KEY (
			TITLE_NO
		);

ALTER TABLE TITLE
	ADD
		CONSTRAINT UK_TITLE
		UNIQUE (
			TITLE_NAME
		);

/* 부서 */
CREATE TABLE DEPARTMENT (
	DEPT_NO NUMBER NOT NULL, /* 부서번호 */
	DEPT_NAME VARCHAR2(20), /* 부서명 */
	FLOOR NUMBER(2) /* 위치 */
);

COMMENT ON TABLE DEPARTMENT IS '부서';

COMMENT ON COLUMN DEPARTMENT.DEPT_NO IS '부서번호';

COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '부서명';

COMMENT ON COLUMN DEPARTMENT.FLOOR IS '위치';

CREATE UNIQUE INDEX PK_DEPARTMENT
	ON DEPARTMENT (
		DEPT_NO ASC
	);

CREATE UNIQUE INDEX UIX_DEPARTMENT
	ON DEPARTMENT (
		DEPT_NAME ASC
	);

ALTER TABLE DEPARTMENT
	ADD
		CONSTRAINT PK_DEPARTMENT
		PRIMARY KEY (
			DEPT_NO
		);

ALTER TABLE DEPARTMENT
	ADD
		CONSTRAINT UK_DEPARTMENT
		UNIQUE (
			DEPT_NAME
		);

/* 사원 */
CREATE TABLE EMPLOYEE (
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	EMP_NAME VARCHAR2(20) NOT NULL, /* 사원명 */
	TNO NUMBER, /* 직책 */
	MANAGER NUMBER, /* 직속상사 */
	SALARY NUMBER, /* 급여 */
	DNO NUMBER, /* 부서 */
	HIREDATE DATE /* 입사일 */
);

COMMENT ON TABLE EMPLOYEE IS '사원';

COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '사원번호';

COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '사원명';

COMMENT ON COLUMN EMPLOYEE.TNO IS '직책';

COMMENT ON COLUMN EMPLOYEE.MANAGER IS '직속상사';

COMMENT ON COLUMN EMPLOYEE.SALARY IS '급여';

COMMENT ON COLUMN EMPLOYEE.DNO IS '부서';

COMMENT ON COLUMN EMPLOYEE.HIREDATE IS '입사일';

CREATE UNIQUE INDEX PK_EMPLOYEE
	ON EMPLOYEE (
		EMP_NO ASC
	);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT PK_EMPLOYEE
		PRIMARY KEY (
			EMP_NO
		);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT FK_TITLE_TO_EMPLOYEE
		FOREIGN KEY (
			TNO
		)
		REFERENCES TITLE (
			TITLE_NO
		);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_EMPLOYEE
		FOREIGN KEY (
			MANAGER
		)
		REFERENCES EMPLOYEE (
			EMP_NO
		);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT FK_DEPARTMENT_TO_EMPLOYEE
		FOREIGN KEY (
			DNO
		)
		REFERENCES DEPARTMENT (
			DEPT_NO
		);